### ISSUE TITLE
Clear Date

### ISSUE THREAD

**Issue by hanGtz92** [mariomka/vue-datetime#169]
I have tried to add a button to clear the date but failed. Is there some method already?? or can I customize the cancel method?

**Comment by webfelipemaia** [comment]
You can create a component to use as a button within the datetime component.



You can use the DOM to access the input (which I don't think is the Vue.js proposal)

`let myInput = document.getElementById(this.fieldId)`
`myInput.value = ""`

But I think better otherwise...

Follow these steps:
1. Create a component (for example called clearinput-component) containing a button with a prop fieldId that gets the id of the field you want to clear.
`...`
`<button type="button" @click="clearInput">`
`...`
`props: { fieldId: String }`

This component must have a method to retrieve the reference passed in the datetime component.

`methods: { `
`  clearInput() { `
`\\ handle $parent and $children[] depends on the structure of the components`
`      this.$parent.$refs.testInput.$el.$children[0].value="" `
`}`

2. In the datetime component assign:
`:inputId="'your-custom-id"  ref="testInput"`

so we can have

`<datetime type="date" :inputId="'your-custom-id"  ref="testInput">`

The value formed by ref will be retrieved by the clearInput () method.

3. In the template provided by the datetime component you insert the created component
`<template slot="after">`
`  <clearinput-component :fieldId="your-custom-id"  ></clearinput-component>`
`</template>`

Then next to the input will appear the button to clear the date. So _$children[0].value=""_ is the same as using _myInput.value = ""_ as seen in the first example. Here we have _$children[0]_ as more than one element can be retrieved

**Comment by mariomka** [comment]
I hope this is solved. You can re-open the issue if you wish.
