### ISSUE TITLE
How do i load a value into the vue-datetime field

### ISSUE THREAD

**Issue by eliomartinezb** [mariomka/vue-datetime#67]
## Versions
- vue:
- vue-datetime:
- luxon:

### Steps To Reproduce:

Including a reproduction would be great. You can fork this fiddle: https://jsfiddle.net/ofc30uv3/

I have this datetime that works perfectly when i want to create a new event.

```
<datetime v-model="date" ref="date" input-class="form-control" :format="{ year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: '2-digit'}"></datetime>
```
but when i'm trying to load the information, it gives me the following error:

```
this.$refs.date.value = data.results.date;

[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"
```
How do i load the value correctly into the field?

**Comment by bretanac93** [comment]
This is not an issue regarding this plugin but VueJS lack of knowledge, check this out:
https://vuejs.org/v2/guide/computed.html

if you want to set a default value to the date time picker, is enough to assign a string with the date to the related model, sth like this:

```
<template>
  <div><datetime type="datetime" v-model="defaultDate"  /></div>
</template>
<script>
export default {
  data() {
    return {
      defaultDate: '2018-02-22T12:20:00.001Z'
    }
  }
}
</script>
```

Now, if you have the datepicker inside a child component and you are passing the default date as property, then besides `data` you have to use also `computed` properties for modifying `defaultDate` value, this Warn vue is throwing you is because if you modify the data inside the child component through the property and the component re-render you will loose the modification.
Hope it helps.
Cheers.
